POS-master/posproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posapp.urls")),
  
]

posapp/urls.py
from django.urls import path
from .views import *

app_name = 'posapp'



urlpatterns = [
    path('',indexview.as_view(),name='index'),
    path('index', LoginView.as_view(), name='login'),
    path('home/',HomeView.as_view(),name = 'home'),
    path('logout/',LogoutView.as_view(),name = 'logout'),
    #supplier
    path('supplier/list/', SupplierListView.as_view(), name='supplierlist'),
    path('admin/student/create', SupplierCreateView.as_view(), name='studentcreate'),
    path('supplier/update/<int:pk>/',
         SupplierUpdateView.as_view(), name='supplierupdate'),
   path('supplier/delete/<int:pk>/',SupplierdeleteView.as_view(), name='supplierdelete'),


    #customer

    

    
    







]

posproject/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posapp.urls")),
  
]

templates/supplier/supplieradd.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<html>
<head>
    <style>
       
    
    </style>
</head>
<body>
<div class="container">
	
	<div class="row col-1 container">
		<div class="col-md-12">
			<h4>Add supplier</h4>
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn btn-primary">submit</button>

				


			</form>
				
		</div>
		<br>


	</div>
</div>
</body>
</html>

{% endblock %}

templates/supplier/supplierdelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}

<div class="container">
    <br>
	<br>

	<div class="row col-1 container">
		<div class="col-md-12">
			<h4><u>Delete Suppliers</u></h4>
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
                Are you want to delete this supplier ?
				<button class="btn btn-primary">Yes</button>
                <a href="/supplier/list/">Cancel </a>


			</form>

		</div>
		<br>


	</div>
</div>

{% endblock %}

templates/supplier/supplierlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
	<div class="row">
		<div class="col-md-12 table-responsive-sm">
            <br>
			<a href="{% url 'posapp:studentcreate' %}" class="btn btn-info"><i class="fa fa-plus"></i></a>
			
			<table class="table table-bordered">
				<thead style="background-color: yellow;color:black;">
					<tr class="text-dark">
						<th>S.N</th>
						<th>Name</th>
						<th>Address</th>
						<th>Phone</th>
						<th>Mobile_no</th>
						<th>action</th>
				
					</tr>	

				</thead>
				<tbody>
					{% for suppliers in suppliers %}
					<tr style="color: black;">
						<td>{{ forloop.counter }}</td>
						<td>{{ suppliers.name }}</td>
						<td>{{ suppliers.address }}</td>
						<td>{{ suppliers.phone }}</td>
						<td>{{ suppliers.mobile_no }}</td>
					
						<td>
                            <a href="{% url 'posapp:supplierupdate' suppliers.id %}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
							<a href="{% url 'posapp:supplierdelete' suppliers.id %}" class="btn btn-success"><i class="fa fa-trash"></i></a>

						</td>


					</tr>	


					{% endfor %}
				</tbody>
					
			</table>
		</div>
	</div>
{% endblock %}

templates/supplier/supplierupdate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}
{% block content %}
<div class="container">
    <br>
	<br>
    
	<div class="row col-1 container">
		<div class="col-md-12">
			<h4><u>Update Book</u></h4>
			<form method="post" enctype="multipart/form-data">
				{% csrf_token %}
				{{form.as_p}}
				<button class="btn btn-primary">submit</button>

				


			</form>
				
		</div>
		<br>


	</div>
</div>

{% endblock %}